hasla = [
"Transcendencja",
"Szczebrzeszyn",
"Wyimaginowany",
"Imponderabilia",
"Lekkoatletyka",
"Metamorfoza",
"Prima Aprilis",
"Antykoncepcja",
"Antyterrorysta",
"Konstantynopolitański",
"Gżegżółka",
"Rzeżączka",
"Malkontent",
"Emulgacja",
"Emulacja",
"Onomatopeja",
"Oksymoron",
"Tranzystor",
"Florystyka",
"Ekstrapolacja",
"Frywolne zakonnice",
"Antyterrorystyczne karaluchy",
"Aleksandryjskie królestwo",
"Wyimaginowany konsultant",
"Rubieżne rusałki",
"Europarlamentarzysta ortodoksyjny",
"Gawiedź onieśmielona",
"Chędogi apartamentowiec",
"Podatek katastralny",
"Ewidencja podatkowa",
"Kwas Deoksyrybonukleinowy",
"Anatomopatologiczny",
"Pięćdziesięciogroszówka",
"Luminescencja",
"Magnetoelektryczny",
"Rzeżucha",
"Skrzyżowanie",
"Ekwilibrystyka",
"Prokrastynacja",
"Toksoplazmoza",
"Morena",
"Polisacharyd",
"Promieniotwórczość",
"Franczyzobiorca",
"Ambiwalentny",
"Interlokutor",
"Konfabulacja",
"Prokrastynacja",
"Tenatologia",
"Egalitaryzm",
"Dźwiękonaśladownictwo",
"Dwudziestogroszówka",
"Niepodległościowiec",
"Lumpenproletariat",
"Wyselekcjonowany",
"Przeintelektualizować",
"Średniozmineralizowana",
"Niepodległościowiec",
"Niezdyscyplinowanie",
"Międzykontynentalny",
"Demokratyczna Republika Konga",
"Wielka Odsiecz Wiedeńska",
"Propaganda polityczna",
"Alexander Graham Bell",
"Antykomunistyczny",
]